# Generated by Django 5.2.5 on 2025-10-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullanicilar', '0002_auto_20250814_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='onaylandi',
            field=models.BooleanField(default=True, verbose_name='Hesap Onaylandı'),
        ),
    ]
