# Generated by Django 5.2.5 on 2025-10-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullanicilar', '0003_alter_profil_onaylandi'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='adres',
            field=models.TextField(blank=True, null=True, verbose_name='Adres'),
        ),
        migrations.AddField(
            model_name='profil',
            name='telefon',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon Numarası'),
        ),
    ]
