# Generated by Django 5.2.5 on 2025-10-13 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kullanicilar', '0004_profil_adres_profil_telefon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='adres',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='telefon',
        ),
    ]
