# Generated by Django 5.2.5 on 2025-10-13 09:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullanicilar', '0005_remove_profil_adres_remove_profil_telefon'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='kayit_tarihi',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
