# Generated by Django 5.2.5 on 2025-10-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullanicilar', '0006_profil_kayit_tarihi'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='telefon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
