# Generated by Django 5.2.5 on 2025-10-14 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kullanicilar', '0007_profil_telefon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='telefon',
        ),
    ]
