# Generated by Django 5.2.5 on 2025-10-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullanicilar', '0008_remove_profil_telefon'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='telefon',
            field=models.CharField(blank=True, max_length=15, verbose_name='Telefon Numarası'),
        ),
    ]
