# Generated by Django 5.2.5 on 2025-10-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullanicilar', '0009_profil_telefon'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='eski_kullanici',
            field=models.BooleanField(default=False, verbose_name='Eski Kullanıcı'),
        ),
    ]
