# Generated by Django 5.2.5 on 2025-10-14 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kullanicilar', '0010_profil_eski_kullanici'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='eski_kullanici',
        ),
    ]
