# Generated by Django 5.2.5 on 2025-10-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullanicilar', '0011_remove_profil_eski_kullanici'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='ozel_erisim',
            field=models.BooleanField(default=False, verbose_name='Özel Erişim'),
        ),
    ]
