# Generated by Django 5.2.5 on 2025-10-12 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dersler', '0009_remove_ders_materyal_remove_kurs_gorsel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sinav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(default='Sertifika Sınavı', max_length=200)),
                ('fiyat', models.DecimalField(decimal_places=2, default=150.0, max_digits=10, verbose_name='Fiyat (EURO)')),
            ],
        ),
        migrations.CreateModel(
            name='Paket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Paket Başlığı')),
                ('aciklama', models.TextField(verbose_name='Paket Açıklaması')),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat (TL)')),
                ('kurslar', models.ManyToManyField(to='dersler.kurs', verbose_name='İçerdiği Kurslar')),
            ],
        ),
        migrations.CreateModel(
            name='SinavSiparisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('odeme_tamamlandi', models.BooleanField(default=False)),
                ('sinav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odeme.sinav', verbose_name='Sınav')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
        migrations.CreateModel(
            name='Siparis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('odeme_tamamlandi', models.BooleanField(default=False)),
                ('paket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odeme.paket', verbose_name='Satın Alınan Paket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
    ]
