# Generated by Django 5.2.5 on 2025-10-12 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odeme', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siparis',
            name='paket',
        ),
        migrations.RemoveField(
            model_name='siparis',
            name='user',
        ),
        migrations.DeleteModel(
            name='Paket',
        ),
        migrations.DeleteModel(
            name='Siparis',
        ),
    ]
