# Generated by Django 5.2.5 on 2025-10-12 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odeme', '0002_remove_siparis_paket_remove_siparis_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EgitimPaketi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Paket Başlığı')),
                ('aciklama', models.TextField(blank=True, verbose_name='Paket Açıklaması')),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat (TL)')),
                ('aktif', models.BooleanField(default=True, verbose_name='Satışta Mı?')),
            ],
            options={
                'verbose_name': 'Eğitim Paketi',
                'verbose_name_plural': 'Eğitim Paketleri',
            },
        ),
        migrations.CreateModel(
            name='Siparis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('adres', models.TextField(verbose_name='Adres')),
                ('telefon', models.CharField(max_length=15, verbose_name='Telefon Numarası')),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('odeme_tamamlandi', models.BooleanField(default=False, verbose_name='Ödeme Tamamlandı')),
                ('paket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odeme.egitimpaketi', verbose_name='Satın Alınan Paket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kurs Siparişi',
                'verbose_name_plural': 'Kurs Siparişleri',
            },
        ),
    ]
