# Generated by Django 5.2.5 on 2025-10-12 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odeme', '0003_egitimpaketi_siparis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siparis',
            name='paket',
        ),
        migrations.RemoveField(
            model_name='siparis',
            name='user',
        ),
        migrations.DeleteModel(
            name='EgitimPaketi',
        ),
        migrations.DeleteModel(
            name='Siparis',
        ),
    ]
