# Generated by Django 5.2.5 on 2025-10-13 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dersler', '0010_remove_kurs_herkese_acik_and_more'),
        ('odeme', '0004_remove_siparis_paket_remove_siparis_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinavsiparisi',
            name='sinav',
        ),
        migrations.RemoveField(
            model_name='sinavsiparisi',
            name='user',
        ),
        migrations.CreateModel(
            name='Paket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Paket Başlığı')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Paket Açıklaması')),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat (EURO)')),
                ('kurslar', models.ManyToManyField(to='dersler.kurs', verbose_name='İlişkili Kurslar')),
            ],
        ),
        migrations.CreateModel(
            name='Siparis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('odeme_tamamlandi', models.BooleanField(default=False)),
                ('ad', models.CharField(max_length=100, verbose_name='Ad')),
                ('soyad', models.CharField(max_length=100, verbose_name='Soyad')),
                ('telefon', models.CharField(max_length=20, verbose_name='Telefon Numarası')),
                ('adres', models.TextField(verbose_name='Adres')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('paket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odeme.paket', verbose_name='Paket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
        migrations.DeleteModel(
            name='Sinav',
        ),
        migrations.DeleteModel(
            name='SinavSiparisi',
        ),
    ]
