# Generated by Django 5.2.5 on 2025-10-13 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odeme', '0005_remove_sinavsiparisi_sinav_remove_sinavsiparisi_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sinav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(default='Sertifika Sınavı', max_length=200)),
                ('fiyat', models.DecimalField(decimal_places=2, default=150.0, max_digits=10, verbose_name='Fiyat (EURO)')),
            ],
        ),
        migrations.RemoveField(
            model_name='siparis',
            name='paket',
        ),
        migrations.RemoveField(
            model_name='siparis',
            name='user',
        ),
        migrations.CreateModel(
            name='SinavSiparisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Ad')),
                ('soyad', models.CharField(max_length=100, verbose_name='Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('telefon', models.CharField(max_length=20, verbose_name='Telefon Numarası')),
                ('adres', models.TextField(verbose_name='Adres')),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('odeme_tamamlandi', models.BooleanField(default=False)),
                ('sinav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odeme.sinav', verbose_name='Sınav')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
        migrations.DeleteModel(
            name='Paket',
        ),
        migrations.DeleteModel(
            name='Siparis',
        ),
    ]
