# Generated by Django 5.2.5 on 2025-10-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odeme', '0008_kitap_kitapsiparisi'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitap',
            name='fotograf',
            field=models.ImageField(blank=True, null=True, upload_to='kitap_kapaklari/', verbose_name='Kitap Kapağı'),
        ),
    ]
