# Generated by Django 5.2.5 on 2025-10-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odeme', '0009_kitap_fotograf'),
    ]

    operations = [
        migrations.AddField(
            model_name='egitimpaketi',
            name='fotograf',
            field=models.ImageField(blank=True, null=True, upload_to='egitim_paketi_kapaklari/', verbose_name='Paket Kapağı'),
        ),
    ]
