# Generated by Django 5.2.5 on 2025-10-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odeme', '0010_egitimpaketi_fotograf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egitimpaketi',
            name='fiyat',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat (TL)'),
        ),
        migrations.AlterField(
            model_name='kitap',
            name='fiyat',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat (TL)'),
        ),
    ]
