# Generated by Django 5.2.5 on 2025-11-30 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odeme', '0011_alter_egitimpaketi_fiyat_alter_kitap_fiyat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paketsiparisi',
            name='paket',
        ),
        migrations.RemoveField(
            model_name='paketsiparisi',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sinavsiparisi',
            name='sinav',
        ),
        migrations.RemoveField(
            model_name='sinavsiparisi',
            name='user',
        ),
        migrations.CreateModel(
            name='Sepet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='Oturum Anahtarı')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
        migrations.CreateModel(
            name='SepetUrunu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adet', models.PositiveIntegerField(default=1, verbose_name='Adet')),
                ('kitap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odeme.kitap', verbose_name='Kitap')),
                ('sepet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='odeme.sepet')),
            ],
        ),
        migrations.CreateModel(
            name='Siparis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Ad')),
                ('soyad', models.CharField(max_length=100, verbose_name='Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('telefon', models.CharField(max_length=20, verbose_name='Telefon Numarası')),
                ('adres', models.TextField(verbose_name='Teslimat Adresi')),
                ('toplam_tutar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Toplam Tutar')),
                ('tarih', models.DateTimeField(auto_now_add=True, verbose_name='Sipariş Tarihi')),
                ('durum', models.CharField(choices=[('hazirlaniyor', 'Hazırlanıyor'), ('kargoya_verildi', 'Kargoya Verildi'), ('tamamlandi', 'Tamamlandı'), ('iptal', 'İptal Edildi')], default='hazirlaniyor', max_length=20, verbose_name='Sipariş Durumu')),
                ('kargo_takip_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kargo Takip No')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Sipariş',
                'verbose_name_plural': 'Siparişler',
                'ordering': ['-tarih'],
            },
        ),
        migrations.CreateModel(
            name='SiparisUrunu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Satış Fiyatı')),
                ('adet', models.PositiveIntegerField(default=1)),
                ('kitap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odeme.kitap', verbose_name='Kitap')),
                ('siparis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='odeme.siparis')),
            ],
        ),
        migrations.DeleteModel(
            name='KitapSiparisi',
        ),
        migrations.DeleteModel(
            name='PaketSiparisi',
        ),
        migrations.DeleteModel(
            name='Sinav',
        ),
        migrations.DeleteModel(
            name='SinavSiparisi',
        ),
    ]
