# Generated by Django 5.2.5 on 2025-12-01 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odeme', '0012_remove_paketsiparisi_paket_remove_paketsiparisi_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EgitimPaketi',
        ),
    ]
