# Generated by Django 5.2.5 on 2025-12-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odeme', '0013_delete_egitimpaketi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kitap',
            options={'ordering': ['sira']},
        ),
        migrations.AddField(
            model_name='kitap',
            name='onizleme_dosyasi',
            field=models.FileField(blank=True, null=True, upload_to='kitap_onizlemeleri/', verbose_name='Önizleme Dosyası (PDF)'),
        ),
        migrations.AddField(
            model_name='kitap',
            name='sira',
            field=models.IntegerField(default=0, verbose_name='Sıralama'),
        ),
    ]
