# Generated by Django 5.2.5 on 2025-12-06 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odeme', '0014_alter_kitap_options_kitap_onizleme_dosyasi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndirimKodu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=20, unique=True, verbose_name='İndirim Kodu')),
                ('indirim_orani', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='İndirim Oranı (%)')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('kullanim_sayisi', models.IntegerField(default=0, verbose_name='Kullanım Sayısı')),
                ('maksimum_kullanim', models.IntegerField(default=0, verbose_name='Maksimum Kullanım (0 sınırsız)')),
                ('son_kullanim_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Son Kullanım Tarihi')),
            ],
            options={
                'verbose_name': 'İndirim Kodu',
                'verbose_name_plural': 'İndirim Kodları',
            },
        ),
        migrations.AddField(
            model_name='sepet',
            name='uygulanan_indirim_kodu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='odeme.indirimkodu', verbose_name='Uygulanan İndirim Kodu'),
        ),
        migrations.AddField(
            model_name='siparis',
            name='indirim_kodu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='odeme.indirimkodu', verbose_name='Kullanılan İndirim Kodu'),
        ),
    ]
