# Generated by Django 5.2.5 on 2025-12-07 00:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odeme', '0015_indirimkodu_sepet_uygulanan_indirim_kodu_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indirimkodu',
            options={},
        ),
        migrations.RemoveField(
            model_name='indirimkodu',
            name='kullanim_sayisi',
        ),
        migrations.RemoveField(
            model_name='indirimkodu',
            name='maksimum_kullanim',
        ),
        migrations.RemoveField(
            model_name='indirimkodu',
            name='son_kullanim_tarihi',
        ),
        migrations.RemoveField(
            model_name='sepet',
            name='uygulanan_indirim_kodu',
        ),
        migrations.RemoveField(
            model_name='siparis',
            name='indirim_kodu',
        ),
        migrations.AddField(
            model_name='indirimkodu',
            name='gecerlilik_tarihi',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Son Kullanma Tarihi'),
        ),
        migrations.AddField(
            model_name='sepet',
            name='uygulanan_kupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='odeme.indirimkodu', verbose_name='Uygulanan Kupon'),
        ),
        migrations.AddField(
            model_name='siparis',
            name='kullanilan_kupon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Kullanılan Kupon Kodu'),
        ),
        migrations.AlterField(
            model_name='indirimkodu',
            name='aktif',
            field=models.BooleanField(default=True, verbose_name='Aktif mi?'),
        ),
        migrations.AlterField(
            model_name='indirimkodu',
            name='indirim_orani',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='İndirim Oranı (%)'),
        ),
        migrations.AlterField(
            model_name='indirimkodu',
            name='kod',
            field=models.CharField(max_length=50, unique=True, verbose_name='Kupon Kodu'),
        ),
    ]
