# Generated by Django 5.2.5 on 2025-12-07 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odeme', '0016_alter_indirimkodu_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indirimkodu',
            name='kullanim_limiti',
            field=models.PositiveIntegerField(default=0, verbose_name='Kullanım Limiti (0 = Sınırsız)'),
        ),
        migrations.AddField(
            model_name='indirimkodu',
            name='kullanim_sayisi',
            field=models.PositiveIntegerField(default=0, verbose_name='Kullanılma Sayısı'),
        ),
    ]
