# Generated by Django 5.2.5 on 2025-12-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odeme', '0017_indirimkodu_kullanim_limiti_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siparis',
            name='iyzico_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='İyzico İşlem ID'),
        ),
        migrations.AddField(
            model_name='siparis',
            name='odeme_tamamlandi',
            field=models.BooleanField(default=False, verbose_name='Ödeme Tamamlandı mı?'),
        ),
        migrations.AddField(
            model_name='siparis',
            name='tc_kimlik',
            field=models.CharField(default='11111111111', max_length=11, verbose_name='TC Kimlik No'),
        ),
    ]
