# Generated by Django 5.2.5 on 2025-12-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odeme', '0018_siparis_iyzico_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siparis',
            name='posta_kodu',
            field=models.CharField(default='34000', max_length=10, verbose_name='Posta Kodu'),
        ),
        migrations.AddField(
            model_name='siparis',
            name='sehir',
            field=models.CharField(default='İstanbul', max_length=50, verbose_name='Şehir'),
        ),
        migrations.AddField(
            model_name='siparis',
            name='ulke',
            field=models.CharField(default='Turkey', max_length=50, verbose_name='Ülke'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='tc_kimlik',
            field=models.CharField(max_length=11, verbose_name='TC Kimlik No'),
        ),
    ]
