# Generated by Django 5.2.5 on 2025-12-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odeme', '0019_siparis_posta_kodu_siparis_sehir_siparis_ulke_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siparis',
            name='posta_kodu',
            field=models.CharField(max_length=10, verbose_name='Posta Kodu'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='sehir',
            field=models.CharField(max_length=50, verbose_name='Şehir'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='ulke',
            field=models.CharField(max_length=50, verbose_name='Ülke'),
        ),
    ]
