# Generated by Django 5.2.5 on 2025-12-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odeme', '0020_alter_siparis_posta_kodu_alter_siparis_sehir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitap',
            name='stok',
            field=models.PositiveIntegerField(default=0, verbose_name='Stok Adedi'),
        ),
    ]
