# Generated by Django 5.2.5 on 2025-12-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odeme', '0021_kitap_stok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siparis',
            name='durum',
            field=models.CharField(choices=[('hazirlaniyor', 'Hazırlanıyor'), ('kargoya_verildi', 'Kargoya Verildi'), ('tamamlandi', 'Tamamlandı'), ('iptal', 'İptal Edildi'), ('stok_hatasi', 'Stok Hatası (Ödeme Alındı)')], default='hazirlaniyor', max_length=20, verbose_name='Sipariş Durumu'),
        ),
    ]
