# Generated by Django 5.2.5 on 2026-01-05 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odeme', '0022_alter_siparis_durum'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitapGorsel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gorsel', models.ImageField(upload_to='kitap_detay_gorseller/', verbose_name='Ekstra Görsel')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('kitap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ekstra_gorseller', to='odeme.kitap')),
            ],
            options={
                'verbose_name': 'Kitap Görseli',
                'verbose_name_plural': 'Kitap Görselleri (Galeri)',
                'ordering': ['sira'],
            },
        ),
        migrations.CreateModel(
            name='KitapVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(blank=True, max_length=200, verbose_name='Video Başlığı')),
                ('dosya', models.FileField(upload_to='kitap_videolar/', verbose_name='Video Dosyası')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('kitap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videolar', to='odeme.kitap')),
            ],
            options={
                'verbose_name': 'Kitap Videosu',
                'verbose_name_plural': 'Kitap Videoları',
                'ordering': ['sira'],
            },
        ),
    ]
