# Generated by Django 5.2.5 on 2026-01-08 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odeme', '0023_kitapgorsel_kitapvideo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='siparis',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Oturum Anahtarı'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
    ]
