# Generated by Django 5.2.5 on 2025-10-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KitapKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, verbose_name='İsim')),
                ('soyisim', models.CharField(max_length=100, verbose_name='Soyisim')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta Adresi')),
                ('telefon', models.CharField(max_length=20, verbose_name='Telefon Numarası')),
                ('kayit_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
            ],
            options={
                'verbose_name': 'Kitap Kaydı',
                'verbose_name_plural': 'Kitap Kayıtları',
                'ordering': ['-kayit_tarihi'],
            },
        ),
    ]
