# Generated by Django 5.2.5 on 2025-08-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oyun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Oyun Başlığı')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Kısa Açıklama')),
                ('embed_kodu', models.TextField(verbose_name='Oyun Gömme Kodu (iframe)')),
                ('sira_numarasi', models.PositiveIntegerField(default=0, verbose_name='Sıra Numarası')),
            ],
            options={
                'verbose_name': 'Oyun',
                'verbose_name_plural': 'Oyunlar',
                'ordering': ['sira_numarasi'],
            },
        ),
    ]
