# Generated by Django 5.2.5 on 2025-08-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyunlar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oyun',
            name='gorsel',
            field=models.ImageField(blank=True, null=True, upload_to='oyun_gorselleri/', verbose_name='Oyun Görseli (Kapak Fotoğrafı)'),
        ),
    ]
