# Generated by Django 5.2.5 on 2025-08-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyunlar', '0002_oyun_gorsel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oyun',
            name='gorsel',
        ),
        migrations.AddField(
            model_name='oyun',
            name='sadece_uyelere_ozel',
            field=models.BooleanField(default=False, verbose_name='Sadece Üyelere Özel mi?'),
        ),
    ]
