# Generated by Django 5.2.5 on 2025-10-04 13:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogYazisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Başlık')),
                ('icerik', ckeditor.fields.RichTextField(verbose_name='İçerik')),
                ('sira_numarasi', models.PositiveIntegerField(default=0, verbose_name='Sıra Numarası')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blog Yazısı',
                'verbose_name_plural': 'Blog Yazıları',
                'ordering': ['sira_numarasi'],
            },
        ),
    ]
