# Generated by Django 5.2.5 on 2026-01-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogyazisi',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='URL Yolu (Otomatik Oluşur)'),
        ),
    ]
