# Generated by Django 5.2.5 on 2026-01-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogyazisi_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogyazisi',
            name='gorsel',
            field=models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Kapak Görseli'),
        ),
        migrations.AddField(
            model_name='blogyazisi',
            name='gorsel_alt_metni',
            field=models.CharField(blank=True, help_text='Görme engelliler ve Google için görseli anlatan kısa bir cümle.', max_length=255, null=True, verbose_name='Görsel Alt Metni (SEO)'),
        ),
        migrations.AddField(
            model_name='blogyazisi',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Açıklaması'),
        ),
        migrations.AddField(
            model_name='blogyazisi',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Başlığı (Google)'),
        ),
    ]
