# Generated by Django 5.2.5 on 2025-08-14 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Kurs Başlığı')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Kurs Açıklaması')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
            },
        ),
        migrations.CreateModel(
            name='Ders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Ders Başlığı')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Ders Açıklaması')),
                ('vimeo_video_id', models.CharField(help_text='Vimeo linkindeki sayıyı girin (örn: 123456789)', max_length=20, verbose_name='Vimeo Video ID')),
                ('sira_numarasi', models.PositiveIntegerField(default=0, help_text='Derslerin hangi sırada gösterileceğini belirler.', verbose_name='Sıra Numarası')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dersler', to='dersler.kurs', verbose_name='Ait Olduğu Kurs')),
            ],
            options={
                'verbose_name': 'Ders',
                'verbose_name_plural': 'Dersler',
                'ordering': ['sira_numarasi'],
            },
        ),
    ]
