# Generated by Django 5.2.5 on 2025-08-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dersler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurs',
            name='gorsel',
            field=models.ImageField(blank=True, null=True, upload_to='kurs_gorselleri/', verbose_name='Kurs Görseli'),
        ),
    ]
