# Generated by Django 5.2.5 on 2025-08-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dersler', '0003_kurs_herkese_acik_kurs_izinli_kullanicilar'),
    ]

    operations = [
        migrations.AddField(
            model_name='ders',
            name='test_embed_kodu',
            field=models.TextField(blank=True, help_text="Quizlet'ten alınan iframe kodunu buraya yapıştırın.", null=True, verbose_name='Test Gömme Kodu (iframe)'),
        ),
    ]
