# Generated by Django 5.2.5 on 2025-08-17 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dersler', '0004_ders_test_embed_kodu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ders',
            name='test_embed_kodu',
        ),
    ]
