# Generated by Django 5.2.5 on 2025-08-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dersler', '0005_remove_ders_test_embed_kodu'),
    ]

    operations = [
        migrations.AddField(
            model_name='ders',
            name='etkinlik_embed_kodu',
            field=models.TextField(blank=True, help_text='Wordwall gibi sitelerden alınan iframe kodunu buraya yapıştırın.', null=True, verbose_name='Etkinlik Gömme Kodu (iframe)'),
        ),
    ]
