# Generated by Django 5.2.5 on 2025-08-17 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dersler', '0006_ders_etkinlik_embed_kodu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ders',
            name='etkinlik_embed_kodu',
        ),
    ]
