# Generated by Django 5.2.5 on 2025-10-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dersler', '0007_remove_ders_etkinlik_embed_kodu'),
    ]

    operations = [
        migrations.AddField(
            model_name='ders',
            name='materyal',
            field=models.FileField(blank=True, null=True, upload_to='ders_materyalleri/', verbose_name='Ders Materyali (PDF, vb.)'),
        ),
    ]
