# Generated by Django 5.2.5 on 2025-10-06 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dersler', '0008_ders_materyal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ders',
            name='materyal',
        ),
        migrations.RemoveField(
            model_name='kurs',
            name='gorsel',
        ),
    ]
