# Generated by Django 5.2.5 on 2025-10-13 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dersler', '0009_remove_ders_materyal_remove_kurs_gorsel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kurs',
            name='herkese_acik',
        ),
        migrations.RemoveField(
            model_name='kurs',
            name='izinli_kullanicilar',
        ),
    ]
