# Generated by Django 5.2.5 on 2025-10-13 07:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dersler', '0010_remove_kurs_herkese_acik_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kurs',
            name='herkese_acik',
            field=models.BooleanField(default=True, verbose_name='Herkese Açık'),
        ),
        migrations.AddField(
            model_name='kurs',
            name='izinli_kullanicilar',
            field=models.ManyToManyField(blank=True, related_name='erisilebilen_kurslar', to=settings.AUTH_USER_MODEL, verbose_name='İzinli Kullanıcılar'),
        ),
    ]
