# Generated by Django 5.2.5 on 2025-08-17 19:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sayfa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Sayfanın URL'de görünecek kimliğidir. Örn: 'hakkimizda'", unique=True)),
                ('baslik', models.CharField(max_length=200, verbose_name='Sayfa Başlığı')),
                ('icerik', ckeditor.fields.RichTextField(verbose_name='Sayfa İçeriği')),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Son Güncellenme')),
            ],
            options={
                'verbose_name': 'Sayfa',
                'verbose_name_plural': 'Sayfalar',
            },
        ),
    ]
