# Generated by Django 5.2.5 on 2025-10-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RehberVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Rehber Video Başlığı')),
                ('vimeo_video_id', models.CharField(help_text='Vimeo linkindeki sayıyı girin (örn: 123456789)', max_length=20, verbose_name='Vimeo Video ID')),
                ('aktif', models.BooleanField(default=True, verbose_name='Ana Sayfada Gösterilsin mi?')),
            ],
            options={
                'verbose_name': 'Rehber Videosu',
                'verbose_name_plural': 'Rehber Videoları',
            },
        ),
    ]
