# Generated by Django 5.2.5 on 2025-10-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0002_rehbervideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rehbervideo',
            name='sayfa',
            field=models.CharField(choices=[('anasayfa', 'Ana Sayfa'), ('blog', 'Blog Sayfası')], default='anasayfa', max_length=10, verbose_name='Görüneceği Sayfa'),
        ),
        migrations.AlterField(
            model_name='rehbervideo',
            name='aktif',
            field=models.BooleanField(default=True, verbose_name='Bu Video Aktif mi?'),
        ),
    ]
