# Generated by Django 5.2.5 on 2025-12-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0003_rehbervideo_sayfa_alter_rehbervideo_aktif'),
    ]

    operations = [
        migrations.CreateModel(
            name='IletisimTalebi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta Adresi')),
                ('telefon', models.CharField(max_length=20, verbose_name='Telefon Numarası')),
                ('mesaj', models.TextField(blank=True, null=True, verbose_name='Mesaj')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
            ],
            options={
                'verbose_name': 'İletişim Talebi',
                'verbose_name_plural': 'İletişim Talepleri',
                'ordering': ['-olusturulma_tarihi'],
            },
        ),
    ]
