# Generated by Django 5.2.5 on 2026-03-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0004_iletisimtalebi'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaSayfaAyar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslangic_fiyat', models.CharField(default='10.000 TL', max_length=50, verbose_name='Başlangıç Paketi Fiyatı')),
                ('orta_fiyat', models.CharField(default='20.000 TL', max_length=50, verbose_name='Orta Paket Fiyatı')),
                ('premium_fiyat', models.CharField(default='24.000 TL', max_length=50, verbose_name='Premium Paket Fiyatı')),
                ('konusma_fiyat', models.CharField(default='10.000 TL', max_length=50, verbose_name='Konuşma Paketi Fiyatı')),
            ],
            options={
                'verbose_name': 'Ana Sayfa Fiyat Ayarı',
                'verbose_name_plural': 'Ana Sayfa Fiyat Ayarları',
            },
        ),
    ]
