# Generated by Django 5.2.5 on 2026-04-09 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0005_anasayfaayar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anasayfaayar',
            name='baslangic_fiyat',
        ),
        migrations.RemoveField(
            model_name='anasayfaayar',
            name='orta_fiyat',
        ),
    ]
